### ISSUE TITLE
Homebridge isn't connecting to home app if I add this to my config

### ISSUE THREAD

**Issue by tamasvicsotka** [ToddGreenfield/homebridge-nut#10]
Homebridge isn't connecting to home app if I add this to my config. I can't see any issue but It is not working.

**Comment by ToddGreenfield** [comment]
What errors does the log show?

**Comment by ToddGreenfield** [comment]
Update to the latest version just pushed and try again.

**Comment by AndySwitcher** [comment]
I have same issue. I received the error:

[2018-06-20 23:30:12] [Nut] Initializing Nut platform...
[2018-06-20 23:30:12] [Nut] Starting Nut Platform on localhost:3493. Polling (seconds): 120
[2018-06-20 23:30:22] [Nut] Received Nut accessory #0 main (IPPON) from the Nut platform.
[2018-06-20 23:30:22] [Nut] Initializing platform accessory 'Ippon'...

/usr/local/lib/node_modules/homebridge-nut/index.js:263
                        .setCharacteristic(Characteristic.Model, this.accVars["device.model"].trim() || this.accVars["ups.productid"] || 'No Model#');
                                                                        ^
TypeError: Cannot read property 'trim' of undefined
    at Object.getServices (/usr/local/lib/node_modules/homebridge-nut/index.js:263:73)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:408:36)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:394:32)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Object.accessories (/usr/local/lib/node_modules/homebridge-nut/index.js:77:4)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:384:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:328:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)

pi@raspberrypi:~ $ upsc main
Init SSL without certificate database
battery.voltage: 13.70
battery.voltage.high: -1.08
battery.voltage.low: -0.87
device.type: ups
driver.name: blazer_usb
driver.parameter.pollinterval: 2
driver.parameter.port: auto
driver.parameter.synchronous: no
driver.version: 2.7.4
driver.version.internal: 0.12
input.frequency: 50.3
input.voltage: 223.4
input.voltage.fault: 223.4
output.voltage: 223.4
ups.beeper.status: enabled
ups.delay.shutdown: 30
ups.delay.start: 180
ups.load: 6
ups.productid: 5161
ups.status: OL
ups.temperature: 25.0
ups.type: offline / line interactive
ups.vendorid: 0665

**Comment by ToddGreenfield** [comment]
Has this been resolved?

**Comment by chyuaner** [comment]
I have same issue. But my friend is success.

I found my UPS connect info is very very very few.
JS is crash because can't get "device.model".

I fix this code. Please check my pull request #16 .

<img width="1680" alt="螢幕快照 2019-07-21 下午5 32 52 (c)" src="https://user-images.githubusercontent.com/2195746/61589632-60b45b00-abdf-11e9-89b5-50ba851866be.png">
In image: Left side is my friend. Right side is mine.
